def COLOR_MAP = [
    'SUCCESS': 'good', // Slack color code for successful builds
    'FAILURE': 'danger', // Slack color code for failed build
]
pipeline {
    agent any

    environment {
        cluster = "vproprod"
        service = "vproappprodsvc"
    }

    stages {
        stage('Deploy to ECS Prod') {
            steps {
                // Deploy the application to ECS produciton cluster
                withAWS(credentials: 'awscreds', region: 'us-west-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment' // Update ECS service to force a new deployment
                } 
            }
        }
    }
    post {
        always {
            // Send a Slack notification after the pipeline completes
            echo 'Slack Notification.' // Log message indicating Slack notification is being sent
            slackSend channel: '#devopscicd', // Slack channel to send the notification to
                color: COLOR_MAP[currentBuild.currentResult], // Set the notification color based on build result
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}" // Format the Slack message with build details
        }
    }
}
